apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dk0ssh9bh-go
  janus-idp.io/tekton: dk0ssh9bh-go
  backstage.io/kubernetes-id: dk0ssh9bh-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dk0ssh9bh-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
