apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dk0ssh9bh-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dk0ssh9bh-go 
  name: dk0ssh9bh-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dk0ssh9bh-go 
